export const COMPANY_DATA = {
  name: "HR Maanagement System",
};

export const ATTENDANCE_DATA = [
  {
    employeeName: "John Peters",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    checkInTime: "7:32 a.m",
    checkOutTime: "3:53 p.m",
    status: "on-time",
  },
  {
    employeeName: "John Peters",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    checkInTime: "7:32 a.m",
    checkOutTime: "3:53 p.m",
    status: "late",
  },
  {
    employeeName: "John Peters",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    checkInTime: "7:32 a.m",
    checkOutTime: "3:53 p.m",
    status: "absent",
  },
  {
    employeeName: "John Peters",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    checkInTime: "7:32 a.m",
    checkOutTime: "3:53 p.m",
    status: "on-time",
  },
  {
    employeeName: "John Peters",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    checkInTime: "7:32 a.m",
    checkOutTime: "3:53 p.m",
    status: "late",
  },
];

export const EMPLOYEE_DATA = [
  {
    employeeName: "John Peters 1",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412AD",
    status: "permanent",
  },
  {
    employeeName: "John Peters 2",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412AB",
    status: "permanent",
  },
  {
    employeeName: "John Peters 3",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412AC",
    status: "permanent",
  },
  {
    employeeName: "John Peters 4",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412WW",
    status: "permanent",
  },
  {
    employeeName: "John Peters 5",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412NN",
    status: "permanent",
  },
  {
    employeeName: "John Peters 6",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412AD",
    status: "permanent",
  },
  {
    employeeName: "John Peters 7",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412AB",
    status: "permanent",
  },
  {
    employeeName: "John Peters 8",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412AC",
    status: "permanent",
  },
  {
    employeeName: "John Peters 9",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412WW",
    status: "permanent",
  },
  {
    employeeName: "John Peters 10",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412NN",
    status: "permanent",
  },
  {
    employeeName: "John Peters 11",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412AD",
    status: "permanent",
  },
  {
    employeeName: "John Peters 12",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412AB",
    status: "permanent",
  },
  {
    employeeName: "John Peters 13",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412AC",
    status: "permanent",
  },
  {
    employeeName: "John Peters 14",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412WW",
    status: "permanent",
  },
  {
    employeeName: "John Peters 15",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412NN",
    status: "permanent",
  },
  {
    employeeName: "John Peters 16",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412NN",
    status: "permanent",
  },
  {
    employeeName: "John Peters 17",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412NN",
    status: "permanent",
  },
  {
    employeeName: "John Peters 18",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412NN",
    status: "permanent",
  },
  {
    employeeName: "John Peters 19",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412NN",
    status: "permanent",
  },
  {
    employeeName: "John Peters 20",
    role: "Finance Manager",
    modeOfWork: "On-Site",
    department: "Sales",
    employeeId: "34565412NN",
    status: "permanent",
  },
];

export const PAYROLL_DATA = [
  {
    employeeName: "John Peters",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Successful",
  },
  {
    employeeName: "Clement Abraham",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Pending",
  },
  {
    employeeName: "John Peters",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Successful",
  },
  {
    employeeName: "Clement Abraham",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Successful",
  },
  {
    employeeName: "John Peters",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Pending",
  },
  {
    employeeName: "Clement Abraham",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Successful",
  },
  {
    employeeName: "John Peters",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Pending",
  },
  {
    employeeName: "Clement Abraham",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Pending",
  },
  {
    employeeName: "John Peters",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Successful",
  },
  {
    employeeName: "Clement Abraham",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Pending",
  },
  {
    employeeName: "John Peters",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Pending",
  },
  {
    employeeName: "Clement Abraham",
    ctc: "$56,900",
    salaryPerMonth: "$2,100",
    deduction: "$50",
    tax: "34565412AD",
    status: "Successful",
  },
];

export const HOLIDAYS_DATA = [
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "New Year",
  },
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "International Programmers' Day",
  },
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "World Cancer Day",
  },
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "April Fool Day",
  },
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "International Programmers' Day",
  },
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "International Day for Biological Diversity",
  },
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "International Friendship Day",
  },
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "International Day of Democracy",
  },
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "World Diabetes Day",
  },
  {
    date: "January 01, 2023",
    day: "Tuesday",
    holidayName: "Merry Chrismas",
  },
];
